---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium-hubble
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cilium-hubble
    release: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - port: hubble-metrics
      interval: 30s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
          action: replace
